### ISSUE TITLE
Streamlabs OBS

### ISSUE THREAD

**Issue by Logerfo** [ratwithacompiler/OBS-multitrack-stream#1]
Does this script work on Streamlabs OBS?
Thank you.

**Comment by ratwithacompiler** [comment]
Nope, Streamlabs OBS doesn't support 3rd party plugins at all but they do have support for Twitch Soundtrack and multitrack audio so I think there's a good chance they might add that as an official feature at some point like OBS will next release.

**Comment by Logerfo** [comment]
Thank you again!
