### ISSUE TITLE
Music on VODs

### ISSUE THREAD

**Issue by NAMVSEYASNO** [ratwithacompiler/OBS-multitrack-stream#6]
I did everything according to the instructions, I created 2 channels through voicemeeter, I made one channel for the main sound, the second channel for the browser and spotify, after that I made the track settings as in your example, and after that I downloaded the script in the same way. I checked the sound on VOD after the stream and music from a separate channel is present there. Did I do something wrong, or this script cannot remove the sound of the channel (music) I need from the VOD stream? I will attach screenshots of settings below. I would be very grateful for the answer
![Screenshot_1](https://user-images.githubusercontent.com/59693388/100046966-3017ad80-2e33-11eb-8fae-0698b49c4427.png)
![Screenshot_2](https://user-images.githubusercontent.com/59693388/100046969-30b04400-2e33-11eb-8232-95887964028a.png)

**Comment by ratwithacompiler** [comment]
This is now a native feature in the OBS UI as of 26.1 RC 1 so no more need for this plugin. 
26.1: https://github.com/obsproject/obs-studio/releases

But looking at your settings it looks good, not sure why that didnt work.
